version: "2.2"
services:
  jobmanager:
    image: flink:1.13.2-scala_2.12-java11
    network_mode: host
#    ports:
#      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        restart-strategy: fixed-delay
        restart-strategy.fixed-delay.attempts: 3
        taskmanager.numberOfTaskSlots: 3
        parallelism.default: 2
#        jobmanager.heap.mb: 2048
#        taskmanager.heap.mb: 2048

  taskmanager:
    image: flink:1.13.2-scala_2.12-java11
    network_mode: host
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        restart-strategy: fixed-delay
        restart-strategy.fixed-delay.attempts: 3
        taskmanager.numberOfTaskSlots: 3
        parallelism.default: 2
#        jobmanager.heap.mb: 2048
#        taskmanager.heap.mb: 2048